In [2]:
import vugrad as vg 
import numpy as np

In [18]:
a = vg.TensorNode(np.random.randn(2, 2))
b = vg.TensorNode(np.random.randn(2, 2))
c = a + b 

print(a.value)


print(c.value)
print(c.source)
print(c.source.inputs[0].value) 
print(a.grad)

[[-1.17098984 -0.03976799]
 [-0.32791296 -0.54763839]]
[[-3.16596779 -0.41972361]
 [-2.52568349 -0.65717609]]
[[-1.17098984 -0.03976799]
 [-0.32791296 -0.54763839]]
[[0. 0.]
 [0. 0.]]
